name: End-to-end tests 🧪

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install and run tests
        run:
          npm install
          npm cypress run

